### ISSUE TITLE
no MURA-v1.0, only MURA-v1.1

### ISSUE THREAD

**Issue by berylyellow** [desimone/Musculoskeletal-Radiographs-Abnormality-Classifier#4]
No MURA-v1.0, only MURA-v1.1, could you share the dataset used in your essay？

**Comment by desimone** [comment]
Sorry, MURA-v1.0 accidentally contained patient data.

**Comment by berylyellow** [comment]
Thank you desimone. Can it work with MURA-v1.1? Where should I change?
